# Generated by Django 5.1.4 on 2024-12-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('passwword', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phoneno', models.TextField()),
            ],
        ),
    ]
